<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<?= HOST_APLIC ?>assets/img/hero-banner/hero-banner-1.png" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<?= HOST_APLIC ?>assets/img/hero-banner/hero-banner-2.png" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

      <!-- Category banner section -->
      <section class="category-banner">
         <div class="container">
            <div class="category-banner-slider carousel-m">
               <div class="item">
                  <div class="slide slide-1">
                     <a href="/categorias?categoria=moda">
                        <div class="caption-info">
                           <div class="card-icon">
                              <img src="assets/img/banner/moda.png" alt="blog">
                           </div>
                           <div class="text-detail">
                              <a href="/categorias?categoria=moda">Moda</a>
                           </div>
                        </div>
                     </a>
                  </div>
               </div>
               <div class="item">
                  <div class="slide slide-2">
                     <a href="/categorias?categoria=eletronicos">
                        <div class="caption-info">
                           <div class="card-icon">
                              <img src="assets/img/banner/eletronicos.png" alt="blog">
                           </div>
                           <div class="text-detail">
                              <a href="/categorias?categoria=eletronicos">Eletronicos</a>
                           </div>
                        </div>
                     </a>
                  </div>
               </div>
               <div class="item">
                  <div class="slide slide-3">
                     <a href="/categorias?categoria=presente_papelaria">
                        <div class="caption-info">
                           <div class="card-icon">
                              <img src="assets/img/banner/presentes_papelaria.png" alt="blog">
                           </div>
                           <div class="text-detail">
                              <a href="/categorias?categoria=presente_papelaria">Presentes/Papelaria</a>
                           </div>
                        </div>
                     </a>
                  </div>
               </div>
               <div class="item">
                  <div class="slide slide-4">
                     <a href="/categorias?categoria=cama_mesa_banho">
                        <div class="caption-info">
                           <div class="card-icon">
                              <img src="assets/img/banner/cama_mesa_banho.png" alt="blog">
                           </div>
                           <div class="text-detail">
                              <a href="/categorias?categoria=cama_mesa_banho">Cama/Mesa/Banho</a>
                           </div>
                        </div>
                     </a>
                  </div>
               </div>
               <div class="item">
                  <div class="slide slide-5">
                     <a href="/vendedores">
                        <div class="caption-info">
                           <div class="card-icon">
                              <img src="assets/img/banner/vendedores.png" alt="blog">
                           </div>
                           <div class="text-detail">
                              <a href="/vendedores">Vendedores</a>
                           </div>
                        </div>
                     </a>
                  </div>
               </div>
            </div>
         </div>
      </section>

      <!-- Novos Produtos -->
      <?php if(isset($this->view->novidades) && !empty($this->view->novidades)) {?>
      <section class="product-design">
         <div class="container">
            <div class="main-heading">
               <h2>novos <span>Produtos </span>
               <small><a href="/novos_produtos">ver todos</a></small>
            </h2>
            </div>
            <div class="row new-slider">
            


            <?php foreach($this->view->novidades as $produto) { 
                    $explode_produto = explode(' ',$produto['nome']);
                    $implode_produto = implode('_',$explode_produto);
               ?>

               <div class="col-lg-4">
                  <a href="/produto/<?= $produto['id'] ?>/<?= $implode_produto ?>">
                  <div class="main-product-box">
                     <div class="product-img">
                        <img src="<?= HOST_APLIC ?><?= $produto['imagem1'] ?>" alt="product">
                     </div>
                     <div class="product-name">
                        <a href="/produto/<?= $produto['id'] ?>/<?= $implode_produto ?>">
                        <?= $produto['nome'] ?>
                        </a>
                     </div>
                     <div class="product-price">
                        <a href="/produto/<?= $produto['id'] ?>/<?= $implode_produto ?>" class="price-number">
                        <span>R$<?php 
                  
                        $preco = $produto['preco'];
                        $precoFormatado = number_format($preco, 2, ',', '');

                        echo $precoFormatado;

                        ?>
                        </span>
                        </a>                        
                     </div>
                  </div>
                  </a>
               </div>

               <?php } ?>

            

            </div>
         </div>
      </section>
      <?php } ?>


      <!-- Produtos Destaques -->
      <?php if(isset($this->view->destaques) && !empty($this->view->destaques)) {?>
      <section class="product-design">
         <div class="container">
            <div class="main-heading">
               <h2>produtos <span>Destaques </span>
               <small><a href="/produtos_destaques">ver todos</a></small>
               </h2>
            </div>
            <div class="row new-slider">
               


            <?php foreach($this->view->destaques as $produto) { 
                    $explode_produto = explode(' ',$produto['nome']);
                    $implode_produto = implode('_',$explode_produto);
               ?>

               <div class="col-lg-4">
                  <a href="/produto/<?= $produto['id'] ?>/<?= $implode_produto ?>">
                  <div class="main-product-box">
                     <div class="product-img">
                        <img src="<?= HOST_APLIC ?><?= $produto['imagem1'] ?>" alt="product">
                     </div>
                     <div class="product-name">
                        <a href="/produto/<?= $produto['id'] ?>/<?= $implode_produto ?>">
                        <?= $produto['nome'] ?>
                        </a>
                     </div>
                     <div class="product-price">
                        <a href="/produto/<?= $produto['id'] ?>/<?= $implode_produto ?>" class="price-number">
                        <span>R$<?php 
                  
                        $preco = $produto['preco'];
                        $precoFormatado = number_format($preco, 2, ',', '');

                        echo $precoFormatado;

                        ?>
                        </span>
                        </a>                        
                     </div>
                  </div>
                  </a>
               </div>

               <?php } ?>


               
            </div>
         </div>
      </section>
      <?php } ?>
      
      <!-- Explore products banner section -->
      <section class="exp-products fadeIn animated">
         <div class="container">
            <div class="explore-img">
               <div class="row">
                  <div class="col-md-12 full-width">
                     <div class="find-custom">
                        <h5>Faça do seu jeito</h5>
                        <h2>por Produto ou Categoria</h2>
                        <p>o que você procura está aqui!</p>
                        <a href="javascript:void(0)" class="search-toggle-btn btn exp-product-btn">Produtos</a>
                        <a href="/categorias" class="btn exp-product-buy-now">Categorias</a>
                        <a href="/vendedores" class="btn exp-product-buy-now">Vendedores</a>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      
      <!-- Back to tpo button -->
      <div class="up-scroll">
         <div class="scroll" id="scroll-top-btn">
            <i class="ti-angle-up"></i>
         </div>
      </div>
      <!-- Newsletter Modal -->
      <div class="modal fade modal-sale" id="discount-modal">
         <div class="modal-dialog modal-dialog-centered news-letter-modal">
            <div class="modal-content">
               <button type="button" class="close" data-dismiss="modal">&times;</button>
               <div class="modal-body">
                  <div class="col-md-12">
                     <div class="modal-img-text">
                        <div class="row">
                           <div class="col-md-6 col-sm-12">
                              <img src="assets/img/banner/newsletter.png" alt="img">
                           </div>
                           <div class="col-md-6 col-sm-12">
                              <div class="modal-text">
                                 <p>It won't get any bigger than this</p>
                                 <h2>Big Sale</h2>
                                 <h3>Enjoy upto 60%off</h3>
                                 <button class="btn">Shop Now!</button>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>