<div class="navbar fixed-top">

    <div class="container mt-1">
        <img src="img/logo.png" class="mb-2" width="100" alt="">

        <div class="links">
            <a class="mx-1 mb-1 botao-log" href="/login">Login</a>
        </div>
    </div>

</div>

<div class="bg-navbar"></div>

<div class="container-fluid cont-princ">
    <div class="container">
        <div class="row mt-5 mb-0 pt-5 pb-0 princ">

            <div class="col-md-7 col-sm-12 d-flex justify-content-center align-items-center">

                <div class="pb-2 text-white">
                    <h1>Incentive o Comércio Local e Transforme sua Compra em uma Experiência <p class="d-inline-block" style="font-weight: bold;">Extraordinária!</p></h1>
                </div>

            </div>

            <div class="col-md-5 col-sm-12">

                <div class="d-flex justify-content-center align-items-center m-3">
                    <img src="assets/img/blog/arte-landing2.png" alt="" style="border-radius: 30px; max-width: 500px; min-width: 300px;">
                </div>
                

            </div>

        </div>
    </div>
</div>

<div class="container-fluid beneficios my-0">
    <div class="container">
        <div class="row">
            <div class="col">
                <img src="assets/img/banner/banner-passo.png" class="w-100" alt="">
            </div>
        </div>
    </div>
</div>

<div class="infos">
<img src="assets/img/blog/baseinf.png" class="w-100 mt-0">

<div class="container-fluid beneficios-2 mt-5">
    <div class="container">
        <div class="row">
            <div class="col p-3 d-flex justify-content-center">
                <ul>

                    <li><h4 class="p-1"><i>Ofertas incríveis!</i></h4></li>
                    <li><h4 class="p-1"><i>Compra que apoia sua cidade!</i></h4></li>
                    <li><h4 class="p-1"><i>Produtos de qualidade, ao alcance de um clique.</i></h4></li>
                    <li><h4 class="p-1"><i>Entrega rápida, comodidade total!</i></h4></li>
                    <li><h4 class="p-1"><i>Conheça o vendedor local, confiança absoluta.</i></h4></li>
                    <li><h4 class="p-1"><i>Economize e apoie a sua comunidade.</i></h4></li>
                    
                </ul>
            </div>
        </div>
    </div>
</div>

<img src="assets/img/blog/basesup.png" class="w-100 mb-0">
</div>

<div class="container-fluid beneficios mt-0 mb-0">
    <div class="container">
        <div class="row">
            <div class="col mt-5">

                <h2>Você está pronto para uma nova era de compras incríveis?</h2>
                <h4 class="ben-2">Cadastre-se hoje na <b class="ben-1">Offer</b> e experimente a facilidade, a qualidade e as <b class="ben-1">ofertas exclusivas</b> que você encontra só aqui. <b class="ben-1">Entregas rápidas</b> e seguras diretamente à sua porta. Conexões autênticas com vendedores da sua própria comunidade! </h4>
                <br>
                <h4 class="ben-1">Não perca a chance de fazer compras de uma maneira <b class="ben-2">totalmente nova e empolgante!</b> Seu registro é o primeiro passo para uma experiência de compra extraordinária. Vamos começar essa jornada juntos!</h4>
                <br>
                <div><a class=" d-inline-block botao-log mx-1" href="/login">Faça o Login</a></div>
                

            </div>
        </div>
    </div>
</div>

<img src="assets/img/blog/baseinf.png" class="w-100 mt-0">

<div class="container beneficios-2 my-5">

    <div class="row">
        <div class="col">
                <h1 class="mb-4"><b>Junte-se à Revolução Local!</b></h1>
                <h4>Registre-se <b>Agora</b> e faça parte da transformação de compras na sua cidade!</h4>
                <div class="my-4">
                    <a class=" d-inline-block foobot botao-log mx-1" href="/login">Faça o Login</a>
                </div>
        </div>
    </div>
    
</div>
<img src="assets/img/blog/basesup.png" class="w-100 mb-0">