		<!-- Login section -->
		<div style="height: 100vh;">
			<div class="login-page">
				<form class="login-form" id="form" action="/autenticar" method="post">
					<div class="form-title">
						<h2>Faça o Login:</h2>                        
					</div>

                    <label class="label-input" for="email">E-mail</label>
					<input class="input-tag" type="email" name="email" id="email" value="teste@teste.com" required>
                    
                    <label class="label-input" for="senha">Senha</label>
                    <input class="input-tag" type="password" name="senha" id="senha" value="SenhaTeste@123" required>
                    <svg id="senha1" onclick="alternarTipoSenha()" xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye senha1"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
                    <svg id="senha2" onclick="alternarTipoSenha()" style="display: none;" xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye-off senha1"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"></path><line x1="1" y1="1" x2="23" y2="23"></line></svg>

                    <?php if(isset($_GET['erro']) && $_GET['erro'] == 'login') { ?>
                    <small class="text-danger">*Usuario e/ou senha invalido(s)!</small>
                    <?php } ?>
                    <?php if(isset($_GET['act']) && $_GET['act'] == 'sucesso') {?>
                    <small class="text-success">Cadastro realizado com Sucesso, faça login!</small>
                    <?php } ?>
                    <?php if(isset($_GET['act']) && $_GET['act'] == 'senha_atualizada') {?>
                    <small class="text-success">Senha atualizada com Sucesso, faça login!</small>
                    <?php } ?>

					<button id="botao" class="botao-form">Entrar</button>
                </form>
			</div>
		</div>

        <script>
            function alternarTipoSenha() {
                var senha = document.getElementById("senha");
                var tipoAtual = senha.type;

                // Alterna para o tipo de entrada oposto
                if (tipoAtual === "password") {
                senha.type = "text";
                } else {
                senha.type = "password";
                }
            }
        </script>