<section class="blog-content sidebar-content">
   <div class="container">
      <div class="row">
         <div class="col-lg-3 col-md-4 col-sm-6 col-12 mb-2 mt-2">
            <div class="blog-post sidebar-blog-post">
               <div class="blog-post-box">
                  <a href="/vendedores">
                     <div class="d-flex justify-content-center">
                        <img src="assets/img/blog/vendedores.png" alt="moda">
                     </div>                        
                     <div class="blog-white-text text-center">
                        <h2 class="m-0">Vendedores</h2>
                     </div>
                  </a>
               </div>
            </div>
         </div>
         <div class="col-lg-3 col-md-4 col-sm-6 col-12 mb-2 mt-2">
            <div class="blog-post sidebar-blog-post">
               <div class="blog-post-box">
                  <a href="/categorias?categoria=moda">
                     <div class="d-flex justify-content-center">
                        <img src="assets/img/blog/moda.png" alt="moda">
                     </div>                        
                     <div class="blog-white-text text-center">
                        <h2 class="m-0">Moda</h2>
                     </div>
                  </a>
               </div>
            </div>
         </div>
         <div class="col-lg-3 col-md-4 col-sm-6 col-12 mb-2 mt-2">
            <div class="blog-post sidebar-blog-post">
               <div class="blog-post-box">
                  <a href="/categorias?categoria=eletronicos">
                     <div class="d-flex justify-content-center">
                        <img src="assets/img/blog/eletronicos.png" alt="eletronicos">
                     </div>
                     <div class="blog-white-text text-center">
                        <h2 class="m-0">Eletronicos</h2>
                     </div>
                  </a>
               </div>
            </div>
         </div>
         <div class="col-lg-3 col-md-4 col-sm-6 col-12 mb-2 mt-2">
            <div class="blog-post sidebar-blog-post">
               <div class="blog-post-box">
                  <a href="/categorias?categoria=presente_papelaria">
                     <div class="d-flex justify-content-center">
                        <img src="assets/img/blog/presentes_papelaria.png" alt="presentes_papelaria">
                     </div>
                     <div class="blog-white-text text-center">
                        <h2 class="m-0">Presentes/Papelaria</h2>
                     </div>
                  </a>
               </div>
            </div>
         </div>
         <div class="col-lg-3 col-md-4 col-sm-6 col-12 mb-2 mt-2">
            <div class="blog-post sidebar-blog-post">
               <div class="blog-post-box">
                  <a href="/categorias?categoria=cama_mesa_banho">
                     <div class="d-flex justify-content-center">
                        <img src="assets/img/blog/cama_mesa_banho.png" alt="cama_mesa_banho">
                     </div>
                     <div class="blog-white-text text-center">
                        <h2 class="m-0">Cama/Mesa/Banho</h2>
                     </div>
                  </a>
               </div>
            </div>
         </div>
         
      </div>
   </div>
</section>