<?php
use App\Controllers\CarrinhoController;
use App\Models\Produto;
use MF\Model\Container;
use MF\Model\Model;
?>


<!-- Shop content section -->
<section class="shop-content sidebar-content">
         <div class="container">
            <h4 style="color: #777777;">Pesquisando por: <i style="color: #e84343;">"<?= $this->view->nome_pesquisa ?>"</i></h4>
            <div class="row">
               <div class="col-lg-12 col-md-12 col-sm-12">
                  <div class="row">
                     <div class="col-md-12">
                        <!-- product sort by -->
                        <div class="sort-by-section">
                           <div class="porduct-filter">
                              <div class="input-group">
                                 <a class="sidebar-toggle-icon" id="sidebar-toggle">
                                    <i class="ti-filter" id="toggleIcon"></i>
                                    </a>
                              </div>
                              <div class="collection-view text-right">
                                 <ul>
                                    <li class="grid-product active">
                                       <a class="grid-menu" data-view="grid-view">
                                       <i class="ti-layout-grid2"></i>
                                       </a>
                                    </li>
                                    <li class="grid-product active">
                                       <a class="grid-menu" data-view="list-view">
                                       <i class="ti-view-list"></i>
                                       </a>
                                    </li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-md-12">
                        <!-- product design -->
                        <div class="product-design shop-product-design">
                           <div class="row">

                           <?php foreach($this->view->pesquisa as $produto) { 
                              $explode_produto = explode(' ',$produto['nome']);
                              $implode_produto = implode('_',$explode_produto);
                           ?>

                              <div class="col-lg-3 col-md-4 col-sm-6 my-2 d-flex justify-content-center product-grid-list grid-view">
                                 
                                 <div class="main-product-box fadeIn animated">
                                    <div class="product-img">
                                       <a href="/produto/<?= $produto['id'] ?>/<?= $implode_produto ?>">
                                       <img src="<?= HOST_APLIC ?><?= $produto['imagem1'] ?>">
                                       </a>
                                    </div>
                                    <div class="product-right-content">
                                       
                                       <div class="product-name">
                                          <a href="/produto/<?= $produto['id'] ?>/<?= $implode_produto ?>">
                                          <?= $produto['nome'] ?>
                                          </a>
                                       </div>
                                       <div class="product-price">
                                          <a href="/produto/<?= $produto['id'] ?>/<?= $implode_produto ?>" class="price-number">
                                          <span>R$<?php 
                                    
                                          $preco = $produto['preco'];
                                          $precoFormatado = number_format($preco, 2, ',', '');

                                          echo $precoFormatado;

                                          ?>
                                          </span>
                                          </a>
                                       </div>
                                    </div>
                                    
                                 </div>
                              </div>

                              <?php } ?>

                           </div>
                           <!-- Pagination -->
                           <?php if($this->view->total_paginas > 1) {?>

                              <ul class="pagination">
                                 <?php if(isset($_GET['page']) && $_GET['page'] > 1) {?>

                                 <li class="pageNumber">
                                    <a href="/pesquisar?pesquisa=<?= $this->view->nome_pesquisa?>" class="prev">
                                       <p
                                          class="ti-angle-double-left"></p>
                                    </a>
                                 </li>

                                 <?php } ?>

                                 <?php 

                                    $pagina_atual = $this->view->pagina_atual;
                                    $range = $this->view->range_paginas;
                                    $inicio = max($pagina_atual - $range, 1);
                                    $final = min($pagina_atual + $range, $this->view->total_paginas);

                                    for($i = $inicio; $i <= $final; $i++) {

                                 ?>

                                 <li class="pageNumber <?php if($i == $pagina_atual) {?> active <?php } ?>">
                                    <a href="/pesquisar?pesquisa=<?= $this->view->nome_pesquisa?>&page=<?= $i ?>">
                                       <p><?= $i ?></p>
                                    </a>
                                 </li>

                                 <?php } ?>
                                 

                                 <?php if(!isset($_GET['page']) || $_GET['page'] != $this->view->total_paginas) {?>
                                 <li class="pageNumber">
                                    <a href="/pesquisar?pesquisa=<?= $this->view->nome_pesquisa?>&page=<?= $this->view->total_paginas ?>" class="next">
                                       <p
                                          class="ti-angle-double-right"></p>
                                    </a>
                                 </li>
                                 <?php } ?>
                              </ul>

                           <?php } ?>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>