<!DOCTYPE html>
<html lang="pt-br">
   <head>
      <title>Offer</title>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="Descubra a conveniência da compra local online! Nosso marketplace une comerciantes locais e compradores, oferecendo um jeito mais fácil e rápido de encontrar os produtos que você adora. Explore uma variedade de lojas locais, apoie os negócios de sua comunidade e diversão da simplicidade das compras online. Junte-se a Offer agora!">
      <meta name="keywords" content="compras locais, mercado local, comercio local online, comprando de comerciantes locais, vendas de produtos locais, lojas locais online, compras de bairro, apoio a comunidade, produtos locais, comprar do comercio local, cassia, minas gerais">
      <meta name="author" content="Matheus Rodrigues">
      <meta name="theme-color" content="#FF4E16">
      <link rel="shortcut icon" type="image/x-icon" href="<?= HOST_APLIC ?>assets/img/icons/favicon.png">
      <!-- google fonts -->
      <!--Font-Family-->
      <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
      
      <link
         href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap"
         rel="stylesheet">
      <!-- jquery ui -->
      <link rel='stylesheet' href='<?= HOST_APLIC ?>assets/css/vendor/jquery-ui.min.css'>
      <!-- Animated ui -->
      <link rel='stylesheet' href='<?= HOST_APLIC ?>assets/css/vendor/animate.min.css'>
      <!-- owl & themify icons -->
      <link rel='stylesheet' href='<?= HOST_APLIC ?>assets/css/vendor/owl-carousel.css'>
      <link rel="stylesheet" href="<?= HOST_APLIC ?>assets/css/vendor/themify-icons.css">
      <link rel="stylesheet" href="<?= HOST_APLIC ?>assets/css/vendor/magnific-popup.css">
      <link rel="stylesheet" href="<?= HOST_APLIC ?>assets/css/vendor/zoomy.css">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="<?= HOST_APLIC ?>assets/css/vendor/bootstrap.css">
      <!-- Main styleshit & responsive css -->
      <link rel="stylesheet" href="<?= HOST_APLIC ?>assets/css/style.css">
      <link rel="stylesheet" href="<?= HOST_APLIC ?>assets/css/responsive.css">
      <!-- Color css -->
      <link rel="stylesheet" id="skin-switcher-css" href="<?= HOST_APLIC ?>assets/css/colors/skin-4.css">
      <!-- Background css -->
      <link rel="stylesheet" id="bg-switcher-css" href="<?= HOST_APLIC ?>assets/css/backgrounds/bg-4.css">

      <link rel="stylesheet" href="<?= HOST_APLIC ?>assets/css/demo-2.css">
      <style>
         body {
            background-image: url(/assets/css/backgrounds/background.svg);
            background-attachment: fixed;
         }
         a {
            text-decoration: none;
            text-transform: none;
         }
         .navbar {
            background: #FFF;
         }
         .bg-navbar {
            height: 50px;
         }
         .link {
            text-transform: none;
            text-decoration: none;
            font-size: 18px;
            font-style: normal;
            color: #4311A4;
            font-weight: bold;
         }
         .separa {
            color:#4311A4;
         }
         .link:hover {
            color: #4377B6;
         }
         .princ {
            min-height: 80vh;
            position: relative;
         }
         .beneficios {
            background: #FFF;
            color: #4311A4;
         }
         .beneficios-2 {
            background: none;
            color: #FFF;
         }
         .infos {
            background-image: url(/assets/css/backgrounds/categoria-back.svg);
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
         }
         .cont-princ {
            background: url(assets/img/blog/basesup.png) center bottom no-repeat;
         }
         .ben-1 {
            color: #4311A4;
         }
         .ben-2 {
            color: #FF4E16;
         }
         .links a.botao-cad, .links a.botao-log {
            padding: 7px 12px !important;
            font-size: 14px !important;
         }
         .botao-cad {
            font-size: 18px;
            color: #FFF;
            padding: 10px 15px;
            border-radius: 50px;
            background: #FF4E16;
            border: 2px solid #FF4E16;
         }
         .botao-cad:hover {
            color: #FF4E16;
            background: none;
         }
         .botao-log {
            font-size: 18px;
            color: #FFF;
            padding: 10px 15px;
            border-radius: 50px;
            background: #4311A4;
            border: 2px solid #4311A4;
         }
         .botao-log:hover {
            color: #4311A4;
            background: none;
         }
         .foobot:hover {
            color: #FFF !important;
         }
      </style>
   </head>
   <body>
      <!-- Preloader -->
      <div class="site-loader" id="caixa-loader">
         <div class="ellipsis" id="loader">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
         </div>
      </div>
      <!-- Scroll top / Back to top -->
      <div class='top'></div>

      <!-- ----------------------------------------------------------------- -->
      <!-- ----------------------------------------------------------------- -->

      <?= $this->content() ?>

      <!-- ----------------------------------------------------------------- -->
      <!-- ----------------------------------------------------------------- -->

      <!-- Jquery JS -->
      <script src="<?= HOST_APLIC ?>assets/js/jquery.js"></script>
      <script src="<?= HOST_APLIC ?>assets/js/jquery-ui.min.js"></script>
      <!-- popper JS -->
      <script src="<?= HOST_APLIC ?>assets/js/popper.js"></script>
      <!-- bootstrap JS -->
      <script src="<?= HOST_APLIC ?>assets/js/bootstrap.js"></script>
      <!-- bootstrap notify JS -->
      <script src="<?= HOST_APLIC ?>assets/js/bootstrap-notify.js"></script>
      <!-- owl-carousel JS -->
      <script src="<?= HOST_APLIC ?>assets/js/owl-carousel.js"></script>
      <!-- slick JS -->
      <script src="<?= HOST_APLIC ?>assets/js/slick.js"></script>
      <!-- Zoom image JS -->
      <script src="<?= HOST_APLIC ?>assets/js/zoomy.js"></script>
      <script src="<?= HOST_APLIC ?>assets/js/jquery.magnific-popup.min.js"></script>
      <!-- Main JS -->
      <script src="<?= HOST_APLIC ?>assets/js/tools.js"></script>
      <script src="<?= HOST_APLIC ?>assets/js/script.js"></script>
   </body>
</html>
